### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [szaghi/FUNDAL#1]
I suggest adding the topics `openacc`, `gpu`, `fortran` in the About section at https://github.com/szaghi/OAFML

**Comment by szaghi** [comment]
@Beliavsky 

Thank you for the suggestions. We have just started some test for porting some our codes, if the tests will go well I will try to improve documentation and other auxiliary aspects.

Cheers

**Comment by szaghi** [comment]
@Beliavsky 

Our preliminary tests sound good, thus we will try to invest some efforts in this library. We have added the topics to this repo as per your suggestion, thank you again.

Cheers
